send_rccm:
    path:     /sendRccm/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:sendRccm,idd:0 }
ajouter_pole:
    path:     /ajouterPole/{idP}
    defaults: { _controller: ParametrageBundle:ParameterPole:ajouterPole,idP:0 }
liste_nomcommercial:
    path:     /index
    defaults: { _controller: ParametrageBundle:ArchiveNomCommerciaux:index }
searchPole:
    path:     /searchPole
    defaults: { _controller: ParametrageBundle:ParameterPole:rechercherPole,idP:0 }
searchNomCommercial:
    path:     /searchNomCommercial
    defaults: { _controller: ParametrageBundle:ArchiveNomCommerciaux:rechercherNomCommercial }
supprimer_pole:
    path:     /supprimerPole/{idP}
    defaults: { _controller: ParametrageBundle:ParameterPole:supprimerPole,idP:0 }
activer_pole:
    path:     /activerPole/{idP}
    defaults: { _controller: ParametrageBundle:ParameterPole:activerPole,idP:0 }    
champ_pole:
    path:     /complementPole/{idC}
    defaults: { _controller: ParametrageBundle:ParameterPole:ajoutComplementPole,idC:0 }
supprimer_ComplementPole:
    path:     /supprimerComplementPole/{idP}
    defaults: { _controller: ParametrageBundle:ParameterPole:supprimerComplementPole,idP:0 }
definirCircuit:
    path:     /definirCircuit/{idC}
    defaults: { _controller: ParametrageBundle:ParameterPole:definirCircuit,idC:0 }
searchCircuit:
    path:     /searchCircuit
    defaults: { _controller: ParametrageBundle:ParameterPole:rechercherCircuit}
searchPiece:
    path:     /searchPiece/{idP}
    defaults: { _controller: ParametrageBundle:ParameterPole:rechercherPiece,idP:0}
supprimer_Circuit:
    path:     /supprimerCircuit/{idC}
    defaults: { _controller: ParametrageBundle:ParameterPole:supprimerCircuit,idC:0}
supprimer_PJ:
    path:     /supprimerPieceJ/{idP}
    defaults: { _controller: ParametrageBundle:ParameterPole:supprimerPiece,idP:0}
definirPieceJointe:
    path: /addPieceToBeJoin/{idP}
    defaults: { _controller: ParametrageBundle:ParameterPole:definirPieceAJoindre,idP:0 }
definirFraisDossier:
    path: /addFraisDossier/{id}
    defaults: { _controller: ParametrageBundle:ParameterPole:definirTarification,id:0 }
editFraisDossier:
    path: /editFraisDossier/{id}
    defaults: { _controller: ParametrageBundle:ParameterPole:definirTarification }    
supprimer_frais:
    path:     /supprimerFrais/{idF}
    defaults: { _controller: ParametrageBundle:ParameterPole:supprimerFrais,idF:0}
searchFrais:
    path:     /searchFrais
    defaults: { _controller: ParametrageBundle:ParameterPole:rechercherFrais }    
listerDossierPole:
    path: /listDossierPole
    defaults: { _controller: ParametrageBundle:TraitementPole:listDossierPole }
traiterDossier:
    path: /traiterDossier/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:traiterDossier}
delivrerDossier:
    path: /delivrerDossier
    defaults: { _controller: ParametrageBundle:TraitementPole:delivrerDossier }
validerDossierChefGreffe:
    path: /validerDossierChefGreffe
    defaults: { _controller: ParametrageBundle:TraitementPole:validerDossierChefGreffe }
definirEtapeCreation:
    path: /definirEtapeCreation/{idE}
    defaults: { _controller: ParametrageBundle:ParameterPole:definirEtapeCreation,idE:0 }
supprimer_Etape:
    path:     /supprimerEtape/{idE}
    defaults: { _controller: ParametrageBundle:ParameterPole:supprimerEtape,idE:0}
menuCreation:
    path: /menuCreation/{active}
    defaults: { _controller: ParametrageBundle:ParameterPole:menuCreation,active:1 }

lister_prefecture:
    path:     /listerPrefecture
    defaults: { _controller: ParametrageBundle:Prefecture:listerPrefecture }

ajout_prefecture:
    path:     /ajoutPrefecture/{idR}
    defaults: { _controller: ParametrageBundle:Prefecture:ajoutPrefecture,idR:0 }
prefecture_edit:
    path:     /editPrefecture/{idPerf}
    defaults: { _controller: ParametrageBundle:Prefecture:editPrefecture }
prefecture_delete:
    path:     /deletePrefecture/{id}
    defaults: { _controller: ParametrageBundle:Prefecture:deletePrefecture }  
lister_sousPrefecture:
    path:     /listerSousPrefecture
    defaults: { _controller: ParametrageBundle:Prefecture:listerSousPrefecture }
ajout_sousPrefecture:
    path:     /ajoutSousPrefecture/{idP}
    defaults: { _controller: ParametrageBundle:Prefecture:ajoutSousPrefecture }
sousPrefecture_edit:
    path:     /editSousPrefecture/{id}
    defaults: { _controller: ParametrageBundle:Prefecture:editSousPrefecture }
sousPrefecture_delete:
    path:     /deleteSousPrefecture/{id}
    defaults: { _controller: ParametrageBundle:Prefecture:deleteSousPrefecture } 
new_sousPrefecture:
    path:     /newSousPrefecture
    defaults: { _controller: ParametrageBundle:Prefecture:newSousPrefecture }
charger_prefecture:
    path:     /chargerPrefecture
    defaults: { _controller: ParametrageBundle:Prefecture:chargerPrefecture }
charger_sousPrefecture:
    path:     /chargerSousPrefecture
    defaults: { _controller: ParametrageBundle:Prefecture:chargerSousPrefecture }  
charger_quartier:
    path:     /chargerQuartier
    defaults: { _controller: ParametrageBundle:Prefecture:chargerQuartier }     
charge_libelle_tarification:
    path:     /chargeLibelleTarification
    defaults: { _controller: ParametrageBundle:ParameterPole:chargeLibelleTarification }
charger_profil:
    path:     /chargerProfil
    defaults: { _controller: ParametrageBundle:Prefecture:chargerProfil }
charger_secteurActivite:
    path: /chargerActivite
    defaults: { _controller: ParametrageBundle:Prefecture:chargerSecteurActivite }
charger_entreprise:
    path:     /chargerEntreprise
    defaults: { _controller: ParametrageBundle:Prefecture:chargerEntreprise }
traiter_pers_morale:
    path:     /traiterPersMorale/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:traiterSocieteCommerciale }
visualiserM0:
    path:     /visualiserM0/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:visualiserM0 }
visualiserChefGreffeM0:
    path:     /visualiserChefGreffeM0/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:visualiserChefGreffeM0 }
visualiserME1:
    path:     /visualiserME1/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:visualiserME1 }
traiter_pers_physique:
    path:     /traiterPersPhysique/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:traiterPersonnePhysique } 
traiter_groupement_interet_economique:
    path:     /traiterGroupement/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:traiterGroupementInteretEconomique }
traiter_demande_nif:
    path:     /traiterDemandeNIF/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:traiterDemandeNIF }
visualiserNIF:
    path:     /visualiserNIF/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:visualiserNIF }
cnss_traiterDossier:
    path:     /traitercnss/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:traitercnss }
visualiserNI:
    path:     /visualiserNI/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:visualiserNI }
traiter_dossier_annonceur:
    path:     /traiterDossierAnnonceur/{idd}
    defaults: { _controller: ParametrageBundle:TraitementPole:traiterDossierAnnonceur }