<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommissionnaireAuCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionnaireAuCompteRepository extends EntityRepository
{
	public function getListCommissaire(){                
        $query=$this->createQueryBuilder('o')
		->where('o.actif = true');
        return $query;
    }
}
