<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentationRepository extends EntityRepository
{
      public function getDocumentations () {
                                        $qb = $this->createQueryBuilder("d")
                                                ->setMaxResults(3)
                                                ->orderBy("d.id",'DESC');
                                              return $qb->getQuery()->getResult();
                        
                    }
     
}
