<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LibelleFormulaireDelivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibelleFormulaireDelivreRepository extends EntityRepository {

    public function getLibelleFormulaireDelivreByPole($pole) {
        $db = $this->createQueryBuilder('l')
                ->where('l.pole =:pole')
                ->setParameters(array('pole' => $pole));
        return $db->getQuery()->getResult();
    }
    
    public function getNomFormulaireDelivre($pole, $libelle) {
        $db = $this->createQueryBuilder('l')
                ->where('l.pole =:pole')->andWhere('lower(l.libelle) like :lbl')
                ->setParameters(array('pole' => $pole,'lbl'=>'%'.$libelle.'%'))
                ->setMaxResults(1);
        return $db->getQuery()->getOneOrNullResult();
    }

}
