<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SituationMatrimonialeTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationMatrimonialeTraductionRepository extends EntityRepository
{
public function getListSituationMatrimonialeByLanque($idLangue){        
        $query=$this->createQueryBuilder('s')->join('s.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }
	
	public function getSituationMatrimonialeTraduction($id,$idLangue)
	{
		$qb = $this->createQueryBuilder('t');

		
		$qb	->where('t.situationMatrimoniale = :idSituationMatrimoniale and t.langue = :idLangue')
			->setParameter('idSituationMatrimoniale', $id)
			->setParameter('idLangue', $idLangue)
		;	
		//echo "<script>alert($id);</script>";
		
		return $qb->getQuery()->getOneOrNullResult();
		
	}
}
