<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SousPrefectureCommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousPrefectureCommuneRepository extends EntityRepository
{
    public function  getListOfSousPrefecture($idP=null){
        $query = $this->createQueryBuilder('sp')->where('sp.actif=true');
        if($idP){
            $query->join('sp.prefecture', 'p')->andWhere('p.id=:idp')->setParameter('idp', $idP);
        }
        return $query;
    }
}
