<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeFonctionCommissaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFonctionCommissaireTraductionRepository extends EntityRepository
{
    public function getListTypeFonctionCommissaireByLanque($idLangue){        
        $query=$this->createQueryBuilder('p')->join('p.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }
    
}
