<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeOperationTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOperationTraductionRepository extends EntityRepository
{    
    public function getListOperationByLanque($idLangue){                
        $query=$this->createQueryBuilder('o')->join('o.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }
    public function getLibelleOperationByLanque($idLangue, $idOp) {
        $qb = $this->createQueryBuilder('t')
                ->leftJoin('t.typeOperation', 'to')
                ->join('t.langue', 'l')
                ->where('l.id = :idl')->andWhere('to.id = :idto')
                ->setParameters(array('idl' => $idLangue, 'idto' => $idOp));
        $query = $qb->getQuery();
        $results = $query->getOneOrNullResult();
        return $results;
    }   
}
