default_service_jurique:
    resource: "@DefaultBundle/Controller/ServiceJuriqueController.php"
    type:     annotation

default_detailreservation:
    resource: "@DefaultBundle/Controller/DetailreservationController.php"
    type:     annotation

default_reservation:
    resource: "@DefaultBundle/Controller/reservationController.php"
    type:     annotation

default_type_operation:
    resource: "@DefaultBundle/Controller/typeOperationController.php"
    type:     annotation

parametrage_archive_nom_commerciaux:
    resource: "@ParametrageBundle/Controller/ArchiveNomCommerciauxController.php"
    type:     annotation

utilisateurs_utilisateurs:
    resource: "@UtilisateursBundle/Controller/UtilisateursController.php"
    type:     annotation
    prefix : /{_locale}

banquemondiale:
    resource: "@BanquemondialeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin

default_bundle:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix : /
parametrage:
    resource: "@ParametrageBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/parametrage

utilisateur_bundle:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/utilisateurs
    
parametrage_bundle:
    resource: "@ParametrageBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/parametrage
    
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/traduction

traduction_route:
    resource: "@TraductionBundle/Controller/"
    type:     annotation
    prefix : /{_locale}/traduction

# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
pageNotFound:
    pattern:  /{path}
    defaults: { _controller: BanquemondialeBundle:PageNotFound:pageNotFound, path: '' }
    requirements:
        path: .*