creerDossier:
    path:     /creerDossier
    defaults: { _controller: BanquemondialeBundle:Shared:index}
editDossier:
    path:     /editDossier/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:editDossier}
dossierEncours:
    path:     /brouillon/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierEnCours,idd:0 }
DossiersDiaspora:
    path:     /DossiersDiaspora
    defaults: { _controller: BanquemondialeBundle:Shared:listerDossierDiaspora }
etapeBrouillon:
    path:     /etapeBrouillon/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:etapeBrouillon }
etapeCreationPole:
    path:     /etapeCreationPole/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:etapeCreationPole }
suivreDossier:
    path:     /suivreDossier
    defaults: { _controller: BanquemondialeBundle:Shared:suivreDossier }    
suiviDossier:
    path:     /help/suivreDossier
    defaults: { _controller: BanquemondialeBundle:HelpDesk:suivreDossier }    
dossierPole:
    path:     /dossierpole/{idS}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierPole,idS:1 }
dossierAValiderChefGreffe:
    path:     /dossieravaliderchefgreffe/{idS}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierAValiderChefGreffe,idS:2 }
dossierValideChefGreffe:
    path:     /dossiervalidechefgreffe/{idS}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierValideChefGreffe,idS:2 } 
capitalSocial:
    path:     /capitalSocial/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:capitalSocial }
editDossierDiaspora:
    path:     /editDossierDiaspora/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:creationDossierPole}
detailsActiviteAnterieure:
    path:     /detailsActiviteAnterieure/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:detailsActiviteAnterieure}
detailsOrigineEI:
    path:     /detailsOrigineEI/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:detailsOrigineEI}
detailsDocACollecter:
    path:     /detailsDocACollecter/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:detailsDocACollecter}
detailsPersonneEngageur:
    path:     /detailsPersonneEngageur/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:detailsPersonneEngageur}
detailsCNSS:
    path:     /detailsCNSS/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:detailsCNSS}
detailsFicheEntreprise:
    path:     /detailsFicheEntreprise/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:detailsFicheEntreprise}
validerDossierDiaspora:
    path:     /validerDossierDiaspora/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:validerDossierDiaspora}
sendDemandModif:
    path:     /sendDemandModif/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:demandeModification}    
fraisDossierPole:
    path: /fraisDossierPole/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:fraisDossierPole }
representant_listerrepresentantpole:
    path:     /listerrepresentantpole/{idd}
    defaults: { _controller: BanquemondialeBundle:Representant:listerRepresentantPole }
    
representant_detailspole:
    path:     /detailsrepresentantPole/{id}
    defaults: { _controller: BanquemondialeBundle:Representant:detailsRepresentantPole }
docToBeCollected:
    path: /documentCollected/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:documentCollected }
pieceJointe:
    path: /pieceJointe/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:pieceJointe }
supprimer_piece:
    path: /pieceJointe/{nomF}/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:supprimerPiece }
viewAllJoinedPiece:
    path: /viewAllJoinedPiece/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:visualiserAllPieceJoined }

upload:
    path: /upload/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:upload }
    
fraisDossier:
    path: /fraisDossier/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:fraisDossier }
   
    
creationEntreprise_supprimer:
    path: /demandecreation/supprimmer/{id}
    defaults: { _controller: BanquemondialeBundle:CreationDossier:supprimer }

adminDocumentation:
    path:     /admin/documentation
    
    defaults: { _controller: "BanquemondialeBundle:DocumentationAdmin:index" }

adminDocumentation_show:
    path:     /admin/documentation/{id}/show
    defaults: { _controller: "BanquemondialeBundle:DocumentationAdmin:show" }

adminDocumentation_new:
    path:     /admin/documentation/new
    defaults: { _controller: "BanquemondialeBundle:DocumentationAdmin:new" }

adminDocumentation_create:
    path:     /admin/documentation/create
    defaults: { _controller: "BanquemondialeBundle:DocumentationAdmin:create" }
    methods: POST

adminDocumentation_edit:
    path:     /admin/documentation/{id}/edit
    defaults: { _controller: "BanquemondialeBundle:DocumentationAdmin:edit" }

adminDocumentation_update:
    path:     /admin/documentation/{id}/update
    defaults: { _controller: "BanquemondialeBundle:DocumentationAdmin:update" }
    methods:  [POST, PUT]

adminDocumentation_delete:
    path:     /admin/documentation/{id}/delete
    defaults: { _controller: "BanquemondialeBundle:DocumentationAdmin:delete" }
    methods:  [POST, DELETE]

documentation_download:
    path:     /admin/documentation/{guideName}/download
    defaults: { _controller: "BanquemondialeBundle:DocumentationAdmin:downloadGuide" }
    
DocumentationFront:
    path:     /front/documentation
    defaults: { _controller: "BanquemondialeBundle:DocumentationFrontEnd:AffichedocumentationFrontEnd" }

    
adminLiensutiles:
    path:     /admin/liensutiles
    defaults: { _controller: "BanquemondialeBundle:LiensutilesAdmin:index" }

adminLiensutiles_show:
    path:     /admin/liensutiles/{id}/show
    defaults: { _controller: "BanquemondialeBundle:LiensutilesAdmin:show" }

adminLiensutiles_new:
    path:     /admin/liensutiles/new
    defaults: { _controller: "BanquemondialeBundle:LiensutilesAdmin:new" }

adminLiensutiles_create:
    path:     /admin/liensutiles/create
    defaults: { _controller: "BanquemondialeBundle:LiensutilesAdmin:create" }
    methods: POST

adminLiensutiles_edit:
    path:     /admin/liensutiles/{id}/edit
    defaults: { _controller: "BanquemondialeBundle:LiensutilesAdmin:edit" }

adminLiensutiles_update:
    path:     /admin/liensutiles/{id}/update
    defaults: { _controller: "BanquemondialeBundle:LiensutilesAdmin:update" }
    methods:  [POST, PUT]

adminLiensutiles_delete:
    path:     /admin/liensutiles/{id}/delete
    defaults: { _controller: "BanquemondialeBundle:LiensutilesAdmin:delete" }
    methods:  [POST, DELETE]
 
LiensutilesFront:
    path:     /front/liensutiles/LiensutilesFrontEnd
    defaults: { _controller: "BanquemondialeBundle:LiensutilesFrontEnd:liensutilesFrontEnd" }

FrontDossierdemande:
    path:     /dossierdemande
    defaults: { _controller: "BanquemondialeBundle:DossierDemandeFrondEnd:lister" }

recherche:
    pattern:  /recherche
    defaults: { _controller: "BanquemondialeBundle:DossierDemandeFrondEnd:rechercheTraitement" }
Administrateur_listerPole:
    path:     /listeradminpole/{idd}
    defaults: { _controller: BanquemondialeBundle:Administrateur:ListeAdministrateurDossier }    
Administrateur_listeradmin:
    path:     /listeradmin/{id}/{idd}
    defaults: { _controller: BanquemondialeBundle:Administrateur:listerAdmin,id:0 }
    
Administrateur_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: BanquemondialeBundle:Administrateur:supprimer }
Associe_listerPole:
    path:     /listerassociepole/{idd}
    defaults: { _controller: BanquemondialeBundle:Associe:ListeAssocieDossier }

    
CommissionnaireAuCompte_listercomCompte:
    path:     /listercomCompte/{id}/{idd}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:listercomCompte,id:0 }
    
CommissionnaireAuCompte_supprimercomCompte:
    path:     /supprimercomCompte/{id}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:supprimerComCompte }
       
CommissionnaireAuCompte_RetirercomCompte:
    path:     /retirerComCompte/{id}/{idd}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:retirerComCompte }
    
CommissionnaireAuCompte_ListeAffectercomCompte:
    path:     /affecterComCompte/{idd}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:listerAffecterComCompte }
CommissionnaireAuCompte_ListerPoleDossier:
    path:     /ComCompteListePole/{idd}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:ListeComCOmpteDossier }

commissaire_index:
    path:     /commissaire/
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:index }

commissaire_new:
    path:     /commissaire/ajouter
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:add }

commissaire_edit:
    path:     /commissaire/{id}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:edit }


commissaire_delete:
    path:     /commissaire/supprimer/{id}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:delete }
    
comm_supprimer:
    path:     /commissaire/supprimerComm/{id}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:supprimerComm }
    
comm_activer:
    path:     /commissaire/activerComm/{id}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:activerComm }
    
Associe_listerassocie:
    path:     /listerassocie/{id}/{idd}
    defaults: { _controller: BanquemondialeBundle:Associe:listerAssocie,id:0 }
    
Associe_supprimer:
    path:     /supprimerassocie/{id}
    defaults: { _controller: BanquemondialeBundle:Associe:supprimer }  

representant_listerrepresentant:
    path:     /listerrepresentant/{id}/{idd}
    defaults: { _controller: BanquemondialeBundle:Representant:listerRepresentant,id:0 }

representant_supprimer:
    path:     /supprimerrepresentant/{id}
    defaults: { _controller: BanquemondialeBundle:Representant:supprimerRepresentant }

representant_ajouter:
    path:     /ajouterrepresentant/{id}
    defaults: { _controller: BanquemondialeBundle:Representant:ajouter}

representant_details:
    path:     /detailsrepresentant/{id}
    defaults: { _controller: BanquemondialeBundle:Representant:detailsRepresentant }

representant_conjoints:
    path:     /conjointsrepresentant/{id}/{idr}
    defaults: { _controller: BanquemondialeBundle:Representant:conjointsRepresentant }  

representant_conjointsupprimer:
    path:     /supprimerconjointsrepresentant/{id}
    defaults: { _controller: BanquemondialeBundle:Representant:supprimerConjoint }
    
CommissionnaireAuCompte_choixCommissaire:
    path:     /choixCommissaire/{idd}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:choixCommissaireAuCompte }        
piecejointe_viewpdf:
    path:     /viewpdf/{idd}/{pdfName}
    defaults: { _controller: BanquemondialeBundle:Shared:viewPdf }
situationTraitementPole:
    path:     /situationTraitementPole/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:situationTraitementPole}
    
situationTraitementDossier:
    path:     /situationTraitementDossier/{idd}
    defaults: { _controller: BanquemondialeBundle:HelpDesk:situationTraitementPole}
    
traiterDemandeModification:
    path:     /traiterDemandeModification/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:traiterDemandeModification}
ajoutCommissaire:
    path:     /ajoutCommissaire/{idd}/{idC}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:ajoutCommissaire,idC:0 }
supprimer_Commissaire:
    path:     /supprimer_Commissaire/{idd}/{idC}
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:supprimerCommissaire } 
    

associe_details:
    path:     /detailsassocie/{id}
    defaults: { _controller: BanquemondialeBundle:Associe:detailsAssocie }

associe_detailspole:
    path:     /detailsassociePole/{id}
    defaults: { _controller: BanquemondialeBundle:Associe:detailsAssociePole }

gestion_caisse:
    path:     /gestionCaisse
    defaults: { _controller: BanquemondialeBundle:Quittance:index }

gestion_caisse_pole:
    path:     /gestionCaissePole
    defaults: { _controller: BanquemondialeBundle:Quittance:caissePole }

reporting_quittance:
    path:     /reportingQuittance
    defaults: { _controller: BanquemondialeBundle:Quittance:reporting}

traiter_quittance:
    path:     /traiterQuittance/{idq}
    defaults: { _controller: BanquemondialeBundle:Quittance:charger,idq:0 }

enregistrer_quittance:
    path:     /enregistrerQuittance
    defaults: { _controller: BanquemondialeBundle:Quittance:enregistrer }

visualiser_quittance:
    path:     /visualiserQuittance/{idq}
    defaults: { _controller: BanquemondialeBundle:Quittance:reportQuittance,idq:0 }


formulaire_delivre:
    path:     /visualiserFormulaireDelivre/{idp}/{idd}/{numero}
    defaults: { _controller: BanquemondialeBundle:Shared:reportFormulaireDelivre,idp:0,idd:0,numero:1 }

CommissionnaireAuCompte_loadInfosCom:
    path:     /loadInfosCom
    defaults: { _controller: BanquemondialeBundle:CommissionnaireAuCompte:loadInfosCom } 

brouillard_caisse:
    path:     /brouillardCaisse
    defaults: { _controller: BanquemondialeBundle:Quittance:brouillardCaisse}

repartition_encaissement:
    path:     /repartitionEncaissement
    defaults: { _controller: BanquemondialeBundle:Quittance:repartitionEncaissement}

resumeDossier:
    path:     /resumeDossier/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:resumeDossier}
visualiserP1:
    path: /visualiserP1/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:visualiserP1 }
addActiviteAnterieure:
    path: /addActiviteAnterieure/{idd}
    defaults: { _controller: BanquemondialeBundle:PersPhysique:addActiviteAnterieure }

soumettre_dossier:
    path: /soumettreDossier/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:soumettreDossier }
soumettre_depot:
    path: /soumettreDepot/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:soumettreDepot }
    
path_originepm:
    path: /origine/{idd}
    defaults: { _controller: BanquemondialeBundle:OriginePM:index }
    
conjoint_details:
    path:     /detailsconjoint/{id}
    defaults: { _controller: BanquemondialeBundle:Representant:detailsConjoint }

path_cnss:
    path: /cnss/{idd}
    defaults: { _controller: BanquemondialeBundle:Cnss:index }

createfiche_entreprise:
    path:     /aguipe/create/{idd}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:create }
aguipe_traiterDossier:
    path:     /aguipe/traiter/{idd}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:traiterDossierAguipe }
saisi_traiterDossier:
    path:     /saisi/traiter/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:pieceJointe }
aguipe_visualiserAT:
    path:     /aguipe/visualiserAT/{idd}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:visualiserAttestationDeDeclaration }
aguipe_visualiserFE:
    path:     /aguipe/visualiserFE/{idd}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:visualiserFicheEntreprise }	
documentAccompagnant:
    path:     /documents/{idd}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:listerDocAccompagnant }    
aguipe_visualiserCertRegularite:
    path:     /aguipe/visualiserCertificat/{idd}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:visualiserCertificatRegSociale }  
aguipe_delivrer:
    path:     /aguipe/delivrer
    defaults: { _controller: BanquemondialeBundle:AGUIPE:delivrerDossier }
employe_edit:
    path:     /aguipe/edit/{idd}/{idE}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:editEmploye }

personne_engageur_lister:
    path:     /listerengageur/{id}/{idd}
    defaults: { _controller: BanquemondialeBundle:PersonneEngageur:listerPersonneEngageur,id:0 }

personne_engageur_lister_pole:
    path:     /listerengageurpole/{idd}
    defaults: { _controller: BanquemondialeBundle:PersonneEngageur:listerPersonneEngageurPole }

personne_engageur_supprimer:
    path:     /supprimerengageur/{id}
    defaults: { _controller: BanquemondialeBundle:PersonneEngageur:supprimerPersonneEngageur }
ajout_employe:
    path:     /aguipe/ajoutEmploye/{idd}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:ajoutEmploye }
charger_secteur_activite_creation:
    path: /chargerActivite
    defaults: { _controller: BanquemondialeBundle:Shared:chargerSecteurActivite }
depot_new:
    path:     /depot
    defaults: { _controller: BanquemondialeBundle:Shared:depot}
depot_edit:
    path:     /editDepot/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:editDepot,idd:0}   
lister_depot:
    path:     /listerDepot/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierDepot,idd:0 }
lister_depot_Modification:
    path:     /listerDepotModification/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierDepotModification,idd:0 }
visualiser_AttesPayquittance:
    path:     /visualiserAPQuittance/{idq}
    defaults: { _controller: BanquemondialeBundle:Quittance:reportAttestationPayement,idq:0 }
Visualiser_G1:
    path:     /visualiserG1/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:VisualiserG1,idd:0  }
Formulaire_G1:
    path:     /formulaireG1/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:FormulaireG1,idd:0  }
lister_retrait:
    path:     /listerRetrait/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierRetrait,idd:0 }
    
lister_retrait_partiel:
    path:     /listerRetraitPartiel/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierRetraitPartiel,idd:0 }
    
lister_retirer:
    path:     /listerRetirer/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:listDossierRetirer,idd:0 }
retraitDossier:
    path:     /retraitDossier/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:retraitDossier,idd:0 }
retraitDossierPartiel:
    path:     /retraitDossierPartiel/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:retraitDossierPartiel,idd:0 }
retirerDossier:
    path:     /retirerDossier/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:retirerDossier,idd:0 }
employe_details:
    path:     /employe_details/{idd}/{idE}
    defaults: { _controller: BanquemondialeBundle:AGUIPE:detailsEmploye }
visualiserChefGreffeP1:
    path:     /visualiserChefGreffeP1/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:visualiserChefGreffeP1 }
visualiserChefGreffeG1:
    path:     /visualiserChefGreffeG1/{idd}
    defaults: { _controller: BanquemondialeBundle:Shared:visualiserChefGreffeG1 }
