<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AssocieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssocieRepository extends EntityRepository
{
     public function rechercheByDossierDemande($idDossierDemande = NULL){
        $db = $this->createQueryBuilder('a')               
                ->Join('a.pays', 'p')              
                ->where('a.dossierDemande =:chaine')
              ->setParameters(array('chaine' => $idDossierDemande));
        return $db->getQuery()->getResult();
    }
}
