<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieActiviteRepository extends EntityRepository
{
	public function count($code) {
        return $this->createQueryBuilder('p')
                ->select('count(p)')
                ->where('p.code = :code')
                ->setParameter('code', $code)
                ->getQuery()
                ->getSingleScalarResult();
    }
    public function getListeCategoriesByLangue($idLangue) {
        $query = $this->createQueryBuilder('ca')
                ->join('ParametrageBundle:CategorieActiviteTraduction', 'ct', 'ct.idCategoriActivite')		
		->where('ca.actif = true')
        ->andWhere('ct.langue = :idl')->setParameter('idl', $idLangue)
		->orderBy('ct.libelle','asc');
        $cc=$query->getQuery()->getResult();
        //die(dump($cc));
       
        return $query;
        
    }
}
