<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DossierDemandeCommissionnaireAuCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierDemandeCommissionnaireAuCompteRepository extends EntityRepository
{
	public function findDossierDemandeCommissaire($idd,$langue) {
        $query = $this->createQueryBuilder('ddc')
                ->join('ddc.commissionnaireAuCompte', 'cc')
				->join('ddc.fonction', 'fc')
               		->where('ddc.dossierDemande =:idd')
                ->setParameter('idd', $idd);
      
        $results = $query->getQuery()->getResult();
		
		

        $tabResult = array();
        $i = 0;
        foreach ($results as $result) {
            $tabResult[$i]['id'] = $result->getId();
			$typeFonction = $result->getFonction();
			$tabResult[$i]['fonction'] = $typeFonction;
			$tabResult[$i]['commissionnaireAuCompte'] = $result->getCommissionnaireAuCompte();    

			$idFonc = $result->getFonction();
				
            $typeFonctionTraduction = $this->getEntityManager()->getRepository('BanquemondialeBundle:TypeFonctionCommissaireTraduction')
			->findOneBy(array('langue' => $langue,'typeFonctionCommissaire'=>$typeFonction));
            ($typeFonctionTraduction) ? $tabResult[$i]['typeFonctionTraduction'] = $typeFonctionTraduction->getLibelle() : $tabResult[$i]['typeFonctionTraduction'] = "";
			
            $i++;
        }
        
        return $tabResult;
    }
	
	public function countCommissaire($idd) {
        $query = $this->createQueryBuilder('ddc')		
				->where('ddc.dossierDemande =:idd and ddc.fonction =:fonction')
                ->setParameters(array('idd'=> $idd,'fonction'=>'1'));      
        return sizeof($query->getQuery()->getResult());
    }
	
	public function countCommissaireTitulaire($idd) {
        $query = $this->createQueryBuilder('ddc')		
				->where('ddc.dossierDemande =:idd and ddc.fonction =:fonction')
                ->setParameters(array('idd'=> $idd,'fonction'=>'1'));      
        return sizeof($query->getQuery()->getResult());
    }
	
    /*
    public function countCommissaire($idd) {
        $query = $this->createQueryBuilder('ddc')
                ->join('ddc.commissionnaireAuCompte', 'cc')
				->join('ddc.fonction', 'f')
                 ->join('ddc.dossierDemande', 'd')
		
				->where('d.id =:idd and f.libelle=:libelle or f.libelle=:l')
                ->setParameters(array('idd'=> $idd,'libelle'=>'Titulaire','l'=>'Titular'));
      
        return sizeof($query->getQuery()->getResult());
    }
	*/
}
