<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenreTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreTraductionRepository extends EntityRepository
{
	public function getListGenreByLanque($idLangue){        
        $query=$this->createQueryBuilder('g')->join('g.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }
	
	public function getGenreTraduction($id,$idLangue)
	{
		$qb = $this->createQueryBuilder('t');

		
		$qb	->where('t.genre = :idGenre and t.langue = :idLangue')
			->setParameter('idGenre', $id)
			->setParameter('idLangue', $idLangue)
		;	
		//echo "<script>alert($id);</script>";
		
		return $qb->getQuery()->getOneOrNullResult();
		
	}
}
