<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModePaiementTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModePaiementTraductionRepository extends EntityRepository
{
	public function getListModePaiementByLanque($idLangue){        
        $query=$this->createQueryBuilder('g')->join('g.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }
	
	public function getModePaiementTraduction($id,$idLangue)
	{
		$qb = $this->createQueryBuilder('t');

		
		$qb	->where('t.ModePaiement = :idModePaiement and t.langue = :idLangue')
			->setParameter('idModePaiement', $id)
			->setParameter('idLangue', $idLangue)
		;	
		//echo "<script>alert($id);</script>";
		
		return $qb->getQuery()->getOneOrNullResult();
		
	}


}
