<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModePaiementRepository extends EntityRepository
{
    public function getModePaiement(){
        $query=$this->createQueryBuilder
        ('e')
            ->join('BanquemondialeBundle:ModePaiementTraduction','p')
            ->where("e.id=p.modePaiement");
        return $query;
    }
}
