<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NifRepository extends EntityRepository
{
	public function verifierNumeroIdentificationFiscale($nif, $idd) {
        $db = $this->createQueryBuilder('n')
                ->where('n.numeroIdentificationFiscale = :nif')
                ->andWhere('n.dossierDemande != :idd')
                ->setParameters(array('nif' => $nif, 'idd' =>  $idd));
				//die(dump($db->getQuery()->getResult()));
        return $db->getQuery()->getResult();
    }
	
	public function verifierNumeroFormulaire($numFormulaire, $idd) {
        $db = $this->createQueryBuilder('n')
                ->where('n.numeroFormulaire = :numFormulaire')
                ->andWhere('n.dossierDemande != :idd')
                ->setParameters(array('numFormulaire' => $numFormulaire, 'idd' =>  $idd));
        return $db->getQuery()->getResult();
    }
	
	
}
