<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OriginePMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OriginePMRepository extends EntityRepository
{
	public function rechercheByDossierDemande($idDossierDemande = NULL){
        $db = $this->createQueryBuilder('a')
                //->join('a.fonction', 'b')
                //->Join('a.fonction', 'b')
                //->join('b.fonctionTraduction', 'c')
                ->where('a.dossierDemande =:chaine')
              ->setParameters(array('chaine' => $idDossierDemande));
        return $db->getQuery()->getResult();
    }
}
