<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneEngageurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneEngageurRepository extends EntityRepository {

    public function getPersEngageursByDossierDemande($idd, $idLangue) {
        $qb = $this->createQueryBuilder('r')
                        ->leftJoin('r.dossierDemande', 'd')
                        ->where('d.id = :idd')->setParameters(array('idd' => $idd))->setMaxResults(2);
        $query = $qb->getQuery();
        $results = $query->getResult();
        $tabResult = array();
        $i = 0;
        foreach ($results as $result) {
            $pays = $result->getPays();
            $tabResult[$i]['id'] = $result->getId();
            $tabResult[$i]['nom'] = $result->getNom();
            $tabResult[$i]['prenom'] = $result->getPrenom();
            $tabResult[$i]['dateNaissance'] = $result->getDateDeNaissance();
            $tabResult[$i]['lieuNaissance'] = $result->getLieuDeNaissance();
            $tabResult[$i]['domicile'] = $result->getDomicile();
            
            $tabResult[$i]['nationalite'] = "";
            if ($pays) {
                $paysTrad = $this->getEntityManager()->getRepository('BanquemondialeBundle:PaysTraduction')->findOneBy(array('pays' => $pays->getid(), 'langue' => $idLangue));
                ($paysTrad) ? $tabResult[$i]['nationalite'] = $paysTrad->getNationalite() : $tabResult[$i]['nationalite'] = "";
            }
            $i++;
        }
        return $tabResult;
    }

}
