<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuartierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuartierRepository extends EntityRepository
{
    public function getListOfQuartier($idSP=null)
    {
        $query = $this->createQueryBuilder('q')->where('q.actif=true');
        if($idSP){
            $query->join('q.sousPrefecture', 'sp')->andWhere('sp.id = :idsp')->setParameter('idsp', $idSP);       
        }
       // die(dump($query->getQuery()));
        return $query;
    }
}
