<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository {

    public function getRegionByPays($idPays) {
        $query = $this->createQueryBuilder('t')->join('t.pays', 'l');
        $query->where('l.id = :idp')->setParameter('idp', $idPays);
        return $query;
    }

    public function getRegionByPaysdeResidence() {
        $query = $this->createQueryBuilder('r')->join('r.pays', 'p');
        $query->where('p.residence = true and r.actif=true');
        return $query;
    }

    public function getPays($region, $locale) {
        $pays = $this->_em->getRepository("BanquemondialeBundle:Pays")->find($region->getPays()->getId());
        foreach ($pays->getPaysTraduction() as $traduction) {
            if ($traduction->getLangue()->getCode() == $locale)
                return $traduction->getLibelle();
        }
        return '-';
    }

    public function getRegionResidence() {
        $query = $this->createQueryBuilder('r')
                ->join('r.pays', 'p')
                ->where('p.residence=true');

        return $query;
    }

}
