<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionnaliteTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionnaliteTraductionRepository extends EntityRepository {

		public function getListFonctionnaliteByLanque($idLangue) {
			$query = $this->createQueryBuilder('f')->join('f.langue', 'l')
			->where('l.id = :idl')->setParameter('idl', $idLangue)
			->orderBy('f.libelle','asc');
        return $query;
    }
   

}
