<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionnalitePoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionnalitePoleRepository extends EntityRepository {

    public function getRoutePole($idP, $codeFormJ=null) {
        $query = $this->createQueryBuilder('f')->where('f.pole =:pole')
                ->setParameter('pole', $idP);
        if (isset($codeFormJ)) {
            $query->andWhere('f.codeFormeJuridique=:codeFJ')
                    ->setParameter('codeFJ', $codeFormJ);
        }else{
            $query->andWhere('f.codeFormeJuridique is null');
        }
        $query->setMaxResults(1);
        $firstResult = $query->getQuery()->getOneOrNullResult();
        return $firstResult->getRoute();
    }

}
