<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository {

    public function findNews() {
        $qb = $this->createQueryBuilder('n')
                ->where('n.date_publication <= :pub')
                ->andWhere('n.date_expiration >= :exp')
                ->setParameters(array('pub' => new \Datetime(), 'exp' => new \Datetime()));
        return $qb->getQuery()->getResult();
    }
    

    public function getFiveLastNews() {
        $qb = $this->createQueryBuilder("n")
                ->where('n.date_publication <= :pub')
                ->andWhere('n.date_expiration >= :exp')
                ->orderBy("n.id", 'DESC')
                ->setMaxResults(5)
                ->setParameters(array('pub' => new \Datetime(), 'exp' => new \Datetime()));
        return $qb->getQuery()->getResult();
    }
	
	public function get3LastNews() {
        $qb = $this->createQueryBuilder("n")
                ->where('n.date_publication <= :pub')
                ->andWhere('n.date_expiration >= :exp')
                ->orderBy("n.id", 'DESC')
                ->setMaxResults(3)
                ->setParameters(array('pub' => new \Datetime(), 'exp' => new \Datetime()));
        return $qb->getQuery()->getResult();
    }

}
