<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsTraductionRepository extends EntityRepository
{
     public function findNews($langue) {
        $qb = $this->createQueryBuilder('n')
                ->join('n.langue','l')
                ->join('n.news','t')
                ->where('t.date_publication <= :pub')
                ->andWhere('t.date_expiration >= :exp')
                ->andWhere('l.code = :langue')
                ->setParameters(array('pub' => new \Datetime(), 'exp' => new \Datetime(),'langue'=>$langue));
        return $qb->getQuery()->getResult();
    }
    
    public function getFiveLastNews($langue) {
        $qb = $this->createQueryBuilder("n")
                ->join('n.langue','l')
                ->join('n.news','t')
                ->where('t.date_publication <= :pub')
                ->andWhere('t.date_expiration >= :exp')
                ->andWhere('l.code = :langue')
                ->orderBy("n.id", 'DESC')
                ->setMaxResults(5)
                ->setParameters(array('pub' => new \Datetime(), 'exp' => new \Datetime(),'langue'=>$langue));
        return $qb->getQuery()->getResult();
    }
	
	public function get3LastNews($langue) {
        $qb = $this->createQueryBuilder("n")
                ->join('n.langue','l')
                ->join('n.news','t')
                ->where('t.date_publication <= :pub')
                ->andWhere('t.date_expiration >= :exp')
                ->andWhere('l.code = :langue')
                ->orderBy("n.id", 'DESC')
                ->setMaxResults(3)
                ->setParameters(array('pub' => new \Datetime(), 'exp' => new \Datetime(),'langue'=>$langue));
        return $qb->getQuery()->getResult();
    }
}
