<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoleComplementDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoleComplementDossierRepository extends EntityRepository
{

	public function findComplementAndComplementDossierByPole($idPole,$dossierDemande)
	{
		$query = $this->createQueryBuilder('p')
					->join('ParametrageBundle:ComplementPole','c')
					->where('p.complementpole = c')
					->andWhere('c.pole = :pole')
					->andWhere('p.dossierDemande = :dossierDemande')
					->setParameter('pole', $idPole)
					->setParameter('dossierDemande', $dossierDemande);		
		
		$results = $query->getQuery()->getResult();
		$tabResult = array();
        $i = 0;
        foreach ($results as $result) { 		
            $tabResult[$i]['valeur'] = $result->getValeur();
			$tabResult[$i]['id'] = $result->getComplementpole()->getId();
            $tabResult[$i]['libelle'] = $result->getComplementpole()->getLibelle();			
            $tabResult[$i]['idPole'] = $result->getComplementpole()->getPole();
			$tabResult[$i]['typedonnee'] = $result->getComplementpole()->getTypedonnee();
            $i++;
        }
        return $tabResult;
	}
}
