<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegleRepository extends EntityRepository {
	
	 public function getListReglesByLanque( $idLangue) {     
        // die(dump($datedebut));         
		$sqlQuery='SELECT r.id,r.commissaireRequis as commissairerequis,r.idFormeJuridique,j.sigle,j.libelle,j.idLangue FROM regle r join formeJuridique f on r.idformejuridique = f.id join formeJuridiqueTraduction j on j.idFormeJuridique = f.id where j.idLangue = '.$idLangue;
		
         
		$stmt = $this->getEntityManager()->getConnection()->prepare($sqlQuery);
		$stmt->execute();
   
		//die(dump($stmt));
   
		$results = $stmt->fetchAll();
		
		//die(dump($results));
      
        return $results;
    }

}
