<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SecteurActiviteTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurActiviteTraductionRepository extends EntityRepository
{
     public function getListSecteursByLangue($idLangue) {
        $query = $this->createQueryBuilder('p')->join('p.langue', 'l')
		->join('p.secteurActivite','sa')
		->where('sa.actif = true')
        ->andWhere('l.id = :idl')->setParameter('idl', $idLangue)
		->orderBy('p.libelle','asc');
        return $query;
    }
	
	 public function getListSecteursAndTraduction($idLangue) {
        $query = $this->createQueryBuilder('sat')
		->select('sat,sa,ca,cat')
		->join('sat.langue', 'l')
		->join('sat.secteurActivite','sa')
		->join('sa.categorieActivite','ca')
		->join('ca.categorieActiviteTraduction','cat')
		->where('sa.actif = 1');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue)
		->andWhere('cat.langue = :idl')->setParameter('idl', $idLangue);
		
		//die(dump($query->getQuery()->getResult()));
		
		//die(dump($query->getQuery()->getResult()));
        return $query->getQuery()->getResult();
    }
	
	public function getListSecteursAndTraductionByCategorie($idLangue, $idCategorie) {
        $query = $this->createQueryBuilder('sat')		
		->join('sat.langue', 'l')
		->join('sat.secteurActivite','sa')
		->join('sa.categorieActivite','ca')		
		->where('sa.actif = 1')
		->andWhere('ca.id = :idC')->setParameter('idC', $idCategorie)
        ->andWhere('l.id = :idl')->setParameter('idl', $idLangue);
		
		
		//die(dump($query->getQuery()->getResult()));
        return $query->getQuery()->getResult();
    }
}
