<?php

namespace DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriqueEchangeDNIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueEchangeDNIRepository extends EntityRepository
{
    public function findLastDataSent($numDosier) {
        $query = $this->createQueryBuilder('h')               
                ->where('h.numeroDossier=:num')
                ->setMaxResults(1)
                ->setParameters(array('num' => $numDosier))
                ->orderBy('h.id','Desc');
        $historique = $query->getQuery()->getOneOrNullResult();
        //die(dump($infoPoleSuivant));
        return $historique;
    }
}
