<?php

namespace DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseWSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseWSRepository extends EntityRepository
{
    public function getDescriptionByCode($code)
    {
        $query = $this->createQueryBuilder('r')
                ->where('upper(r.code)=upper(:strCode)')
                ->setParameter('strCode', $code)->setMaxResults(1);
        
        $result=$query->getQuery()->getOneOrNullResult();
        $description="non enegistre";
        if($result){
            $description=$result->getDescription();
        }
        return $description;
    }
    public function getDossierByNomCmmercial($nameCom)
    {
        $query = $this->createQueryBuilder('r')
            ->where('upper(r.denominationSociale)=upper(:strCode)')
            ->setParameter('strCode', $nameCom)->setMaxResults(1);

        $result=$query->getQuery()->getOneOrNullResult();
        $description="Entrprise Inexistante";
        if($result){
            $description=$result->getDescription();
        }
        return $description;
    }
}
