<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArchiveNomCommerciauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveNomCommerciauxRepository extends EntityRepository
{
	public function rechercherNomCommercial($data) {
        $qb = $this->createQueryBuilder('p');
        if ($data['denominationSociale'] != '') {
            $qb->andWhere('p.denominationSociale = :name')->setParameter('name', $data['denominationSociale']);
        }
        $query = $qb->getQuery();
        $results = $query->getResult();
        return $results;
    }
	

	
	
	public function search($data, $page = 0, $max = 10, $getResult = true)
    { 
        $qb = $this->createQueryBuilder('a'); 		
        $query = isset($data['query']) && $data['query']?$data['query']:null; 

		 
        if ($query) {			
            $qb->andWhere('a.denominationSociale like :query') ->setParameter('query', "%".$query."%"); 
			//$qb->setMaxResults($max)->setFirstResult($page * $max); 
        } 
 
        if ($max) { 
            $preparedQuery = $qb->getQuery()->setMaxResults($max)->setFirstResult($page * $max); 
        } else { 
            $preparedQuery = $qb->getQuery(); 
        } 
        return $getResult?$preparedQuery->getResult():$preparedQuery; 
    } 
	
	
	public function archiveNomCommercialExiste($denominationSociale) {
        $qb = $this->createQueryBuilder('a')
        ->where('lower(a.denominationSociale) = lower(:denominationSociale)')
		->setParameter('denominationSociale', $denominationSociale);
        $results = $qb->getQuery()->getResult();
        return $results;
    }


}
