<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieActiviteTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieActiviteTraductionRepository extends EntityRepository
{
     public function getListCategoriesByLangue($idLangue) {
        $query = $this->createQueryBuilder('p')->join('p.langue', 'l')
		->join('p.categorieActivite','ca')
		->where('ca.actif = true')
        ->andWhere('l.id = :idl')->setParameter('idl', $idLangue)
		->orderBy('p.libelle','asc');
        return $query;
    }
	
	 public function getListCategoriesAndTraduction($idLangue) {
        $query = $this->createQueryBuilder('sat')
		->select('sat,sa')
		->join('sat.langue', 'l')
		->join('sat.categorieActivite','sa')
		->where('sa.actif = 1');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
		
		//die(dump($query->getQuery()->getResult()));
        return $query->getQuery()->getResult();
    }
}
