<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentCollectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentCollectedRepository extends EntityRepository
{

public function findDocumentCollectedByParametres($data)
	{	
		$query = $this->createQueryBuilder('a');
		
		if($data['id'] != '')
		{
			$query->andWhere('LOWER(a.id) = :id')
			->setParameter('id', $data['id']);
		}	
		/*		
		if($data['denominationSociale'] != '')
		{
			$query->andWhere('LOWER(a.denominationSociale) like :denominationSociale')
			->setParameter('denominationSociale', '%'.$data['denominationSociale'].'%');
		}
		
		if($data['nomCommercial'] != '')
		{
			$query->andWhere('LOWER(a.nomCommercial) like :nomCommercial')
			->setParameter('nomCommercial', '%'.$data['nomCommercial'].'%');
		}
				
		if($data['dateCreation'] != '')
		{
			$query->andWhere('DATE_DIFF(a.dateCreation,:dateCreation)=0')
			->setParameter('dateCreation', $data['dateCreation']);
		}				
		
		if($data['formeJuridique'] != '')
		{
			$query->andWhere('a.formeJuridique = :formeJuridique')
			->setParameter('formeJuridique', $data['formeJuridique']);
		}
		
		if($data['typeOperation'] != '')
		{
			$query->andWhere('a.typeOperation = :typeOperation')
			->setParameter('typeOperation', $data['typeOperation']);
		}
		*/
		return $query->getQuery()->getResult();

	}

}
