<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSliderRepository extends EntityRepository
{
	public function getAll()
	{
		$qb = $this->createQueryBuilder('n')
                ->where('n.estActive=true')
                ;
        return $qb->getQuery()->getResult();
	}
}
