<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeEntrepriseTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEntrepriseTraductionRepository extends EntityRepository
{
	public function getListTypeEntrepriseByLanque($idLangue) {
        $query = $this->createQueryBuilder('p')->join('p.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }
	
	public function getTypeEntrepriseTraduction($id, $idLangue) {
        $qb = $this->createQueryBuilder('t');


        $qb->where('t.typeEntreprise = :idTypeEntreprise and t.langue = :idLangue')
                ->setParameter('idTypeEntreprise', $id)
                ->setParameter('idLangue', $idLangue)
        ;
     
        return $qb->getQuery()->getOneOrNullResult();
    }
}
