<?php

namespace ParametrageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeOrigineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOrigineRepository extends EntityRepository
{
	public function getTypeOriginePP($siPP){        
        $query=$this->createQueryBuilder('p');
		if($siPP)
		{
			$query->where('p.siPersonnePhysique = true');
		}
        return $query;
    }
}
