<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionPieceJointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionPieceJointeRepository extends EntityRepository {

    public function findAllPieceJoined($idd, $idLangue) {
        $qb = $this->createQueryBuilder('p')->leftJoin('p.dossierDemande', 'd')->addSelect('d')
                        ->where('d.id=:idd')->setParameter('idd', $idd);
        $query = $qb->getQuery();
        $results = $query->getResult();

        $tabResult = array();
        $i = 0;
        $j = 0;
        foreach ($results as $result) {
            $tabResult[$i]['pieceName'] = $result->getPieceName();
            $iddoc = $result->getDocument()->getId();
            $tabResult[$i]['idDoc'] = $iddoc;
            $docTrad = $this->getEntityManager()->getRepository('BanquemondialeBundle:DocumentTraduction')->findOneBy(array('document' => $iddoc, 'langue' => $idLangue));
            ($docTrad) ? $tabResult[$i]['libelleDocument'] = $docTrad->getLibelle() : $tabResult[$i]['libelleDocument'] = "";
            $idRep = $result->getRepresentant();
            $tabResult[$i]['representants'] = array();
            $tabResult[$i]['proprietaire'] = "";
            $tabResult[$i]['fonction'] = "";
            $repEnregistrer = "";
            if ($idRep) {
                $em = $this->getEntityManager();
                $rep = $em->getRepository('BanquemondialeBundle:Representant')->find($idRep);
                $tabResult[$i]['representants'] = $rep;
                $tabResult[$i]['proprietaire'] = ($rep) ? $rep->getPrenom() . " " . $rep->getNom() : "";
                if ($rep) {
                    $fct = ($rep->getFonction()) ? $em->getRepository('BanquemondialeBundle:FonctionTraduction')->findOneBy(array('fonction' => $rep->getFonction(), 'langue' => $idLangue))->getLibelle() : "";
                    $tabResult[$i]['fonction'] = $fct;
                }
                $j = $j + 1;
            }
            if ($idRep) {
                $tabResult[$i]['rowspan'] = $j;
            }else{
                $tabResult[$i]['rowspan'] = 1;
            }
            $i++;
        }
        //die(dump($tabResult));
        return $tabResult;
    }

}
