<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentTraductionRepository extends EntityRepository
{
    public function getListDocumentByLanque($idLangue) {
        $query = $this->createQueryBuilder('d')->join('d.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }
}
