<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentationTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentationTraductionRepository extends EntityRepository {

    public function getDocumentations($langue) {
        $qb = $this->createQueryBuilder("d")
                ->join('d.langue', 'l')
                ->where('l.code = :langue')
                ->setMaxResults(3)
                ->setParameter("langue", $langue)
                ->orderBy("d.id", 'DESC');
        return $qb->getQuery()->getResult();
    }
	
	public function getAllDocumentations($langue) {
        $qb = $this->createQueryBuilder("d")
                ->join('d.langue', 'l')
                ->where('l.code = :langue')               
                ->setParameter("langue", $langue)
                ->orderBy("d.id", 'DESC');
        return $qb->getQuery()->getResult();
    }

}
