<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionTraductionRepository extends EntityRepository {

    public function getListFonctionByLangue($idLangue) {
        $query = $this->createQueryBuilder('f')->join('f.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }

    public function getFonctionTraduction($id, $idLangue) {
        $qb = $this->createQueryBuilder('t');


        $qb->where('t.fonction = :idFonction and t.langue = :idLangue')
                ->setParameter('idFonction', $id)
                ->setParameter('idLangue', $idLangue)
        ;
        //echo "<script>alert($id);</script>";

        return $qb->getQuery()->getOneOrNullResult();
    }
	
	 public function getListFonctionsAndTraduction($idLangue) {
        $query = $this->createQueryBuilder('fct')
		->select('fct,fc')
		->join('fct.langue', 'l')
		->join('fct.fonction','fc');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
		
		//die(dump($query->getQuery()->getResult()));
        return $query->getQuery()->getResult();
    }
}
