<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatutTraitementTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutTraitementTraductionRepository extends EntityRepository
{    
    public function getListStatutTraitementByLangue($idLangue){                
        $query=$this->createQueryBuilder('o')->join('o.langue', 'l');
        $query->where('l.id = :idl')->setParameter('idl', $idLangue);
        return $query;
    }
    
     public function getLibelleStatutTraitementByLangue($idLangue, $idSt) {
        $qb = $this->createQueryBuilder('s')
                ->leftJoin('s.statutTraitement', 'st')
                ->join('s.langue', 'l')
                ->where('l.id = :idl')->andWhere('st.id = :idSt')
                ->setParameters(array('idl' => $idLangue, 'idSt' => $idSt));
        $query = $qb->getQuery();
        $results = $query->getOneOrNullResult();
        return $results;
    }      
}
