<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDossierRepository extends EntityRepository {

    public function getListTypeDossier($idPole, $siglePole = null) {
        $query = $this->createQueryBuilder('t');
        if ($siglePole == "APIP") {
            $query->where('t.enableBySaisi=true');
        } else {
            $query->where('t.pole=:idP')->setParameter("idP", $idPole);
        }
        $query->select('t');

        return $query;
    }

    public function getListeTypeDossierDepot() {
        $query = $this->createQueryBuilder('t')
                ->where('t.enableByDEPOT=true');
        return $query;
    }

}
