<?php

namespace UtilisateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
    public function getProfileByName($name)
    {
        $query = $this->createQueryBuilder('p')
                ->where('p.actif=true')->andWhere('upper(p.nom)=upper(:nom)')
                ->setParameter('nom', $name)->setMaxResults(1);
        
        return $query->getQuery()->getOneOrNullResult();
    }
}
