<?php

namespace UtilisateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends EntityRepository {

    public function findByPole($pole) {
        $qb = $this->createQueryBuilder("u")
                ->where('u.pole =:pole')
                ->setParameter('pole', $pole);
        return $qb->getQuery()->getResult();
    }
    public function findByEntreprise($entreprise) {
        $qb = $this->createQueryBuilder("u")
                ->where('u.entreprise =:entreprise')
                ->setParameter('entreprise', $entreprise);
        return $qb->getQuery()->getResult();
    }
    
  
}
