<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CnssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplementCnssRepository extends EntityRepository
{
	public function rechercheByDossierDemande($idDossierDemande = NULL){
        $db = $this->createQueryBuilder('a')
                ->where('a.dossierDemande =:chaine')
              ->setParameters(array('chaine' => $idDossierDemande));
        return $db->getQuery()->getResult();
    }
}
