<?php

namespace BanquemondialeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionRepository extends EntityRepository
{
public function count($code) {
        return $this->createQueryBuilder('p')
                ->select('count(p)')
                ->where('p.code = :code')
                ->setParameter('code', $code)
                ->getQuery()
                ->getSingleScalarResult();
    }
}
